# Generated by Django 4.1.7 on 2026-01-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfiguration', '0002_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfiguration',
            name='fw_bic',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr BIC'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_email',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Email'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_iban',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr IBAN'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_kdt',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Kommandant'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_konto',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Konto'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_name',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Name'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_nummer',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Feuerwehr Nummer'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_street',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Straße'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_telefon',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Telefon'),
        ),
        migrations.AddField(
            model_name='konfiguration',
            name='fw_webseite',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Webseite'),
        ),
        migrations.AlterField(
            model_name='konfiguration',
            name='fw_ort',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr Ort'),
        ),
        migrations.AlterField(
            model_name='konfiguration',
            name='fw_plz',
            field=models.CharField(default='', max_length=255, verbose_name='Feuerwehr PLZ'),
        ),
    ]
