export interface IFahrzeug {
    id: number,
    name: string,
    kategorie: string,
    reihenfolge: number,
    kuerzel: string,
    fahrzeug: boolean,
    anhaenger: boolean,
    type: string,
    lenkerberechtigung: string,
    stationierung: string,
    personenkapazitaet: number,
    treibstoff: string,
    nutzlast: number,
    ladeflaeche: string,
    ladebordwand: boolean,
    ladekran: boolean,
    wassertank: string,
    wassertankAbnehmbar: boolean,
    geschlossenerAufbau: boolean,
    sonderausstattung: string,
    anhaengervorrichtung: string,
    foto: string
}
