export interface IMassnahme {
    id: number,
    name: string,
    reihenfolge: number,
    kuerzel: string,
    beschreibung: string,
    kategorie: string,
    verantwortung: string,
    verstaendigung: [],
    staerke: number,
    fahrzeuge: [],
    feld1Name: string,
    feld1Value: string,
    feld2Name: string,
    feld2Value: string,
    feld3Name: string,
    feld3Value: string,
    feld4Name: string,
    feld4Value: string,
    feld5Name: string,
    feld5Value: string,
    durchfuehrung: string,
    rueckbau: string
}
