# Generated by Django 4.1.7 on 2025-10-30 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtemschutzMaske',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_nr', models.CharField(max_length=255, verbose_name='Inventar Nummer')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('art', models.CharField(max_length=255, verbose_name='Art')),
                ('typ', models.CharField(max_length=255, verbose_name='Typ')),
                ('eigentuemer', models.CharField(max_length=255, verbose_name='Eigentümer')),
                ('barcode', models.CharField(max_length=255, verbose_name='Barcode')),
                ('baujahr', models.CharField(max_length=255, verbose_name='Baujahr')),
            ],
            options={
                'ordering': ['bezeichnung'],
            },
        ),
    ]
