# Generated by Django 4.1.7 on 2025-10-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atemschutzmaske',
            name='art',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaske',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaske',
            name='baujahr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Baujahr'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaske',
            name='eigentuemer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eigentümer'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaske',
            name='typ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ'),
        ),
    ]
