# Generated by Django 4.1.7 on 2025-10-31 15:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0002_alter_atemschutzmaske_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtemschutzMaskeProtokoll',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(blank=True, max_length=10, null=True, verbose_name='Datum')),
                ('taetigkeit', models.CharField(max_length=255, verbose_name='Tätigkeit')),
                ('verwendung_typ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verwendung Typ')),
                ('verwendung_min', models.BigIntegerField(blank=True, null=True, verbose_name='Verwendung Min')),
                ('wartung_2_punkt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wartung 2 Punkt')),
                ('wartung_unterdruck', models.CharField(blank=True, max_length=255, null=True, verbose_name='Warung Unterdruck')),
                ('wartung_oeffnungsdruck', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wartung Öffnungsdruck')),
                ('wartung_scheibe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wartung Scheibe')),
                ('wartung_ventile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wartung Ventile')),
                ('wartung_maengel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wartung Mängel')),
                ('ausser_dienst', models.BooleanField(default=True)),
                ('name_pruefer', models.CharField(max_length=255, verbose_name='Prüfername')),
                ('austausch', models.JSONField(blank=True, verbose_name='Austausch')),
                ('maske_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atemschutz_masken.atemschutzmaske')),
            ],
            options={
                'ordering': ['datum', 'taetigkeit'],
            },
        ),
    ]
