# Generated by Django 4.1.7 on 2025-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0003_atemschutzmaskeprotokoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='austausch',
            field=models.JSONField(blank=True, null=True, verbose_name='Austausch'),
        ),
    ]
