# Generated by Django 4.1.7 on 2025-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0004_alter_atemschutzmaskeprotokoll_austausch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atemschutzmaske',
            options={'ordering': ['inv_nr']},
        ),
        migrations.RemoveField(
            model_name='atemschutzmaske',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='atemschutzmaskeprotokoll',
            name='austausch',
        ),
        migrations.AddField(
            model_name='atemschutzmaske',
            name='austausch',
            field=models.JSONField(blank=True, null=True, verbose_name='Austausch'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='ausser_dienst',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Außer Dienst'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_2_punkt',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung 2 Punkt'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_maengel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Mängel'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_oeffnungsdruck',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Öffnungsdruck'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_scheibe',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Scheibe'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_unterdruck',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Warung Unterdruck'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='wartung_ventile',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Ventile'),
        ),
    ]
