# Generated by Django 4.1.7 on 2025-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0005_alter_atemschutzmaske_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='datum',
            field=models.DateField(max_length=10, verbose_name='Datum'),
        ),
    ]
