# Generated by Django 4.1.7 on 2025-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0006_alter_atemschutzmaskeprotokoll_datum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atemschutzmaskeprotokoll',
            options={'ordering': ['datum']},
        ),
        migrations.RemoveField(
            model_name='atemschutzmaske',
            name='austausch',
        ),
        migrations.AddField(
            model_name='atemschutzmaskeprotokoll',
            name='tausch_ausatemventil',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Ausatemventil'),
        ),
        migrations.AddField(
            model_name='atemschutzmaskeprotokoll',
            name='tausch_sichtscheibe',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Sichtscheibe'),
        ),
        migrations.AddField(
            model_name='atemschutzmaskeprotokoll',
            name='tausch_sprechmembran',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Sprechmembran'),
        ),
        migrations.AlterField(
            model_name='atemschutzmaskeprotokoll',
            name='taetigkeit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tätigkeit'),
        ),
    ]
