# Generated by Django 4.1.7 on 2025-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_masken', '0007_alter_atemschutzmaskeprotokoll_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atemschutzmaskeprotokoll',
            name='notiz',
            field=models.TextField(blank=True, null=True, verbose_name='Notiz'),
        ),
    ]
