services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        image: mitch122/blaulichtcloud:api-${VERSION}

    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: mitch122/blaulichtcloud:db-${VERSION}

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: mitch122/blaulichtcloud:nginx-${VERSION}
