# Generated by Django 4.1.7 on 2026-01-07 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('bezeichnung', models.CharField(blank=True, default='', max_length=50, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Public Id')),
                ('public_pin_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Public Pin Hash')),
                ('pin_enabled', models.BooleanField(default=False, verbose_name='Pin Aktiv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FahrzeugCheck',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Titel')),
                ('notiz', models.TextField(blank=True, default='', verbose_name='Notiz')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='fahrzeuge.fahrzeug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FahrzeugRaum',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raeume', to='fahrzeuge.fahrzeug')),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RaumItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='Name')),
                ('menge', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('einheit', models.CharField(blank=True, default='', max_length=30, verbose_name='Einheit')),
                ('notiz', models.CharField(blank=True, default='', max_length=255, verbose_name='Notiz')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fahrzeuge.fahrzeugraum')),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FahrzeugCheckItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('missing', 'Fehlt'), ('damaged', 'Beschädigt')], default='ok', max_length=20, verbose_name='Status')),
                ('menge_aktuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Menge Aktuel')),
                ('notiz', models.CharField(blank=True, default='', max_length=255, verbose_name='Notiz')),
                ('fahrzeug_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fahrzeuge.fahrzeugcheck')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fahrzeuge.raumitem', verbose_name='Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
