# Generated by Django 4.1.7 on 2026-01-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahrzeug',
            name='pin_enabled',
        ),
        migrations.RemoveField(
            model_name='fahrzeug',
            name='public_pin_hash',
        ),
    ]
