# Generated by Django 4.1.7 on 2026-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0002_remove_fahrzeug_pin_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fahrzeug',
            options={'ordering': ['name', 'pkid']},
        ),
        migrations.AlterModelOptions(
            name='fahrzeugcheck',
            options={'ordering': ['-created_at', '-pkid']},
        ),
        migrations.AlterModelOptions(
            name='fahrzeugcheckitem',
            options={'ordering': ['pkid']},
        ),
        migrations.AlterModelOptions(
            name='fahrzeugraum',
            options={'ordering': ['reihenfolge', 'pkid']},
        ),
        migrations.AlterModelOptions(
            name='raumitem',
            options={'ordering': ['reihenfolge', 'pkid']},
        ),
        migrations.AlterField(
            model_name='fahrzeugcheckitem',
            name='menge_aktuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Menge Aktuell'),
        ),
    ]
