# Generated by Django 4.1.7 on 2025-04-16 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulKonfiguration',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modul', models.CharField(max_length=255, verbose_name='Modul')),
                ('konfiguration', models.JSONField(blank=True, verbose_name='Konfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
