# Generated by Django 4.1.7 on 2025-10-29 13:52

import core_apps.inventar.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('anzahl', models.IntegerField(blank=True, null=True, verbose_name='Anzahl')),
                ('lagerort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lagerort')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core_apps.inventar.models.inventar_filename, verbose_name='Foto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
