# Generated by Django 4.1.7 on 2025-12-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdftemplate',
            options={'ordering': ['typ', '-version']},
        ),
        migrations.AlterUniqueTogether(
            name='pdftemplate',
            unique_together={('typ', 'bezeichnung', 'version')},
        ),
    ]
