# Generated by Django 4.1.7 on 2025-11-07 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messgeraet',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_nr', models.CharField(max_length=255, verbose_name='Inventar Nummer')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('eigentuemer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eigentümer')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode')),
                ('standort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Standort')),
                ('baujahr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baujahr')),
            ],
            options={
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='MessgeraetProtokoll',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(max_length=10, verbose_name='Datum')),
                ('kalibrierung', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kalibrierung')),
                ('kontrolle_woechentlich', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kontrolle Wöchentlich')),
                ('wartung_jaehrlich', models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Jährlich')),
                ('name_pruefer', models.CharField(max_length=255, verbose_name='Prüfername')),
                ('geraet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messgeraete.messgeraet')),
            ],
            options={
                'ordering': ['datum'],
            },
        ),
    ]
