# Generated by Django 4.1.7 on 2025-04-16 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMD',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hausarzt', models.CharField(max_length=255, verbose_name='Hausarzt')),
                ('letzte_untersuchung', models.CharField(max_length=255, verbose_name='Letzte Untersuchung')),
                ('leistungstest', models.CharField(max_length=255, verbose_name='Leistungstest')),
                ('naechste_untersuchung', models.IntegerField(verbose_name='Nächste Untersuchung')),
                ('tauglichkeit', models.CharField(max_length=55, verbose_name='Tauglichkeit')),
                ('notizen', models.TextField(verbose_name='Notizen')),
                ('fdisk_aenderung', models.DateField(max_length=255, verbose_name='FDISK Änderung')),
                ('mitglied_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitglieder.mitglied')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
