# Generated by Django 4.1.7 on 2025-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmd',
            name='fdisk_aenderung',
            field=models.DateField(blank=True, max_length=10, verbose_name='FDISK Änderung'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='hausarzt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hausarzt'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='leistungstest',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leistungstest'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='letzte_untersuchung',
            field=models.DateField(blank=True, max_length=10, verbose_name='Letzte Untersuchung'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='naechste_untersuchung',
            field=models.IntegerField(blank=True, verbose_name='Nächste Untersuchung'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='notizen',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='tauglichkeit',
            field=models.CharField(blank=True, max_length=55, verbose_name='Tauglichkeit'),
        ),
    ]
