# Generated by Django 4.1.7 on 2025-04-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd', '0002_alter_fmd_fdisk_aenderung_alter_fmd_hausarzt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmd',
            name='fdisk_aenderung',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='FDISK Änderung'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='letzte_untersuchung',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Letzte Untersuchung'),
        ),
        migrations.AlterField(
            model_name='fmd',
            name='naechste_untersuchung',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nächste Untersuchung'),
        ),
    ]
