# Generated by Django 4.1.7 on 2025-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd', '0003_alter_fmd_fdisk_aenderung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmd',
            name='leistungstest_art',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leistungstest Art'),
        ),
    ]
