# Generated by Django 4.1.7 on 2025-10-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd', '0004_fmd_leistungstest_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmd',
            name='hausarzt',
        ),
        migrations.AddField(
            model_name='fmd',
            name='arzt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arzt'),
        ),
        migrations.AddField(
            model_name='fmd',
            name='arzt_typ',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arzttyp'),
        ),
    ]
