# Generated by Django 4.1.7 on 2025-04-16 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stbnr', models.IntegerField(unique=True, verbose_name='Standesbuchnummer')),
                ('vorname', models.CharField(max_length=255, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=255, verbose_name='Nachname')),
                ('svnr', models.CharField(blank=True, max_length=4, verbose_name='Sozialversichungsnummer')),
                ('geburtsdatum', models.DateField(max_length=10, verbose_name='Geburtsdatum')),
            ],
            options={
                'ordering': ['stbnr'],
            },
        ),
    ]
