# Generated by Django 4.1.7 on 2025-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='hauptberuflich',
            field=models.BooleanField(default=False, verbose_name='Hauptberuflich'),
        ),
    ]
