# Generated by Django 4.1.7 on 2025-10-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_geraete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='art',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='baujahr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Baujahr'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='datum_im_dienst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Datum in Dienst gestellt'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='druckminderer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Druckminderer'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='eigentuemer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eigentümer'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='lungenautomat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lungenautomat'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='naechste_gue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nächste Generalüberholung'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='rahmen_nr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rahmen Nummer'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='standort',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraet',
            name='typ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ'),
        ),
    ]
