# Generated by Django 4.1.7 on 2025-11-02 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atemschutz_geraete', '0002_alter_atemschutzgeraet_art_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atemschutzgeraet',
            options={'ordering': ['inv_nr']},
        ),
        migrations.RemoveField(
            model_name='atemschutzgeraet',
            name='bezeichnung',
        ),
        migrations.AddField(
            model_name='atemschutzgeraet',
            name='austausch',
            field=models.JSONField(blank=True, null=True, verbose_name='Austausch'),
        ),
        migrations.CreateModel(
            name='AtemschutzGeraetProtokoll',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(blank=True, max_length=10, null=True, verbose_name='Datum')),
                ('taetigkeit', models.CharField(max_length=255, verbose_name='Tätigkeit')),
                ('verwendung_typ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verwendung Typ')),
                ('verwendung_min', models.BigIntegerField(blank=True, null=True, verbose_name='Verwendung Min')),
                ('wartung_maengel', models.BooleanField(blank=True, default=False, null=True, verbose_name='Wartung Mängel')),
                ('name_pruefer', models.CharField(max_length=255, verbose_name='Prüfername')),
                ('geraet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atemschutz_geraete.atemschutzgeraet')),
            ],
            options={
                'ordering': ['datum', 'taetigkeit'],
            },
        ),
    ]
