# Generated by Django 4.1.7 on 2025-11-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_mitglied_hauptberuflich'),
        ('atemschutz_geraete', '0004_alter_atemschutzgeraetprotokoll_datum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atemschutzgeraetprotokoll',
            options={'ordering': ['datum']},
        ),
        migrations.RemoveField(
            model_name='atemschutzgeraet',
            name='austausch',
        ),
        migrations.RemoveField(
            model_name='atemschutzgeraetprotokoll',
            name='wartung_maengel',
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='geraet_ok',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Gerät OK'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='mitglied_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mitglieder.mitglied'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='preufung_monatlich',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Prüfung Monatlich'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='pruefung_10jahre',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Prüfung 10 Jahre'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='pruefung_jaehrlich',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Prüfung Jährlich'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='tausch_gleitring',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Gleitring'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='tausch_hochdruckdichtring',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Huchdruckdichtring'),
        ),
        migrations.AddField(
            model_name='atemschutzgeraetprotokoll',
            name='tausch_membran',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tausch Membran'),
        ),
        migrations.AlterField(
            model_name='atemschutzgeraetprotokoll',
            name='taetigkeit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tätigkeit'),
        ),
    ]
