# Generated by Django 4.1.7 on 2025-10-16 22:03

import core_apps.news.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('foto', models.ImageField(default='news/default.png', upload_to=core_apps.news.models.news_filename, verbose_name='Foto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
