# Generated by Django 4.1.7 on 2025-10-16 23:19

import core_apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='foto',
            field=models.ImageField(default='', upload_to=core_apps.news.models.news_filename, verbose_name='Foto'),
        ),
    ]
