# Generated by Django 4.1.7 on 2025-10-20 06:57

import core_apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core_apps.news.models.news_filename, verbose_name='Foto'),
        ),
    ]
