# Generated by Django 4.1.7 on 2025-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='typ',
            field=models.CharField(default='intern', max_length=255, verbose_name='Typ'),
        ),
    ]
